#!/bin/sh

# This file is part of OpenPanel - The Open Source Control Panel
# OpenPanel is free software: you can redistribute it and/or modify it 
# under the terms of the GNU General Public License as published by the Free 
# Software Foundation, using version 3 of the License.
#
# Please note that use of the OpenPanel trademark may be subject to additional 
# restrictions. For more information, please visit the Legal Information 
# section of the OpenPanel website on http://www.openpanel.com/

if [ ! -d /etc/postfix ]; then
  echo "Postfix missing"
  echo "quit" >&3
  exit 1
fi


PATH=$PATH:/usr/sbin  # for postconf, just to be sure

postconf -h smtpd_recipient_restrictions | grep -wq 'check_recipient_access hash:/etc/postfix/openpanel/amavis/access' || {
  echo "smtpd_recipient_restrictions incomplete"
  echo "quit" >&3
  exit 1
}

#postconf -h content_filter | grep . && {
#  echo "global content_filter specified, please disable"
#  echo "quit" >&3
#  exit 1
#}

exit 0
